FROM node:14-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY . .
RUN npm run build

FROM nginx 
EXPOSE 80
COPY --from=build /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
