FROM postgres:13.1

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=10 CMD [ "pg_isready", "-q", "-d", "postgres", "-U", "root" ]

COPY scripts/01-init.sh /docker-entrypoint-initdb.d/

VOLUME [ "/data" ]

EXPOSE 5000

CMD ["postgres"]